export const authConsts = {
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILED: "SIGNUP_FAILED",
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FALIURE: 'LOGIN_FALIURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED'
}

export const generalConstatnts = {
    MODE_CHANGE_REQUEST: "MODE_CHANGE_REQUEST",
    SET_MODE_DARK: "SET_MODE_DARK",
    SET_MODE_LIGHT: 'SET_MODE_LIGHT'
}

export const loginConsts = {
    GET_ALL_USER_LOGINS_REQUEST: "GET_ALL_USER_LOGINS_REQUEST",
    GET_ALL_USER_LOGINS_SUCCESS: "GET_ALL_USER_LOGINS_SUCCESS",
    GET_ALL_USER_LOGINS_FAILED: "GET_ALL_USER_LOGINS_FAILED",
    ADD_USER_LOGIN_REQUEST: "ADD_USER_LOGIN_REQUEST",
    ADD_USER_LOGIN_SUCCESS: "ADD_USER_LOGIN_SUCCESS",
    ADD_USER_LOGIN_FAILED: "ADD_USER_LOGIN_FAILED",
    UPDATE_USER_LOGIN_REQUEST: "UPDATE_USER_LOGIN_REQUEST",
    UPDATE_USER_LOGIN_SUCCESS: "UPDATE_USER_LOGIN_SUCCESS",
    UPDATE_USER_LOGIN_FAILED: "UPDATE_USER_LOGIN_FAILED",
    REMOVE_USER_LOGIN_REQUEST: "REMOVE_USER_LOGIN_REQUEST",
    REMOVE_USER_LOGIN_SUCCESS: "REMOVE_USER_LOGIN_SUCCESS",
    REMOVE_USER_LOGIN_FAILED: "REMOVE_USER_LOGIN_FAILED"
}