export const authConsts = {
    KEY_GEN_REQUEST: "KEY_GEN_REQUEST",
    KEY_GEN_SUCCESS: "KEY_GEN_SUCCESS",
    KEY_GEN_FAILED: "KEY_GEN_FAILED",
    USER_DATA_ADD_REQUEST: "USER_DATA_ADD_REQUEST",
    USER_DATA_ADD_SUCCESS: "USER_DATA_ADD_SUCCESS",
    USER_DATA_ADD_FAILED: "USER_DATA_ADD_FAILED",
    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    USER_LOGIN_REQUEST_SUCCESS: "USER_LOGIN_REQUEST_SUCCESS",
    USER_LOGIN_REQUEST_FAILED: "USER_LOGIN_REQUEST_FAILED",
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FALIURE: 'LOGIN_FALIURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED'
}

export const generalConstatnts = {
    MODE_CHANGE_REQUEST: "MODE_CHANGE_REQUEST",
    SET_MODE_DARK: "SET_MODE_DARK",
    SET_MODE_LIGHT: 'SET_MODE_LIGHT'
}

export const loginConsts = {
    GET_ALL_USER_LOGINS_REQUEST: "GET_ALL_USER_LOGINS_REQUEST",
    GET_ALL_USER_LOGINS_SUCCESS: "GET_ALL_USER_LOGINS_SUCCESS",
    GET_ALL_USER_LOGINS_FAILED: "GET_ALL_USER_LOGINS_FAILED",
    ADD_USER_LOGIN_REQUEST: "ADD_USER_LOGIN_REQUEST",
    ADD_USER_LOGIN_SUCCESS: "ADD_USER_LOGIN_SUCCESS",
    ADD_USER_LOGIN_FAILED: "ADD_USER_LOGIN_FAILED",
    UPDATE_USER_LOGIN_REQUEST: "UPDATE_USER_LOGIN_REQUEST",
    UPDATE_USER_LOGIN_SUCCESS: "UPDATE_USER_LOGIN_SUCCESS",
    UPDATE_USER_LOGIN_FAILED: "UPDATE_USER_LOGIN_FAILED",
    REMOVE_USER_LOGIN_REQUEST: "REMOVE_USER_LOGIN_REQUEST",
    REMOVE_USER_LOGIN_SUCCESS: "REMOVE_USER_LOGIN_SUCCESS",
    REMOVE_USER_LOGIN_FAILED: "REMOVE_USER_LOGIN_FAILED",
    REMOVE_LOGINS: "REMOVE_LOGINS",
}

export const vaultConsts = {
    GET_USER_ASSIGN_VAULTS_REQUEST: "GET_USER_ASSIGN_VAULTS_REQUEST",
    GET_USER_ASSIGN_VAULTS_SUCCESS: "GET_USER_ASSIGN_VAULTS_SUCCESS",
    GET_USER_ASSIGN_VAULTS_FAILED: "GET_USER_ASSIGN_VAULTS_FAILED",
    ADD_USER_VAULT_REQUEST: "GET_USER_VAULT_REQUEST",
    ADD_USER_VAULT_SUCCESS: "ADD_USER_VAULT_SUCCESS",
    ADD_USER_VAULT_FAILED: "ADD_USER_VAULT_FAILED",
    UNLOCK_VAULT_REQUEST: "UNLOCK_VAULT_REQUEST",
    UNLOCK_VAULT_SUCCESS: "UNLOCK_VAULT_SUCCESS",
    UNLOCK_VAULT_FAILED: "UNLOCK_VAULT_FAILED",
    LOCK_VAULT_SUCCESS: "LOCK_VAULT_SUCCESS",
    LOCK_VAULT_FAILED: "LOCK_VAULT_FAILED",
    GET_VAULT_DATA_REQUEST: "GET_VAULT_DATA_REQUEST",
    GET_VAULT_DATA_SUCCESS: "GET_VAULT_DATA_SUCCESS",
    GET_VAULT_DATA_FAILED: "GET_VAULT_DATA_FAILED",
    ADD_NEW_VAULT_LOGIN_REQUEST: "ADD_NEW_VAULT_LOGIN_REQUEST",
    ADD_NEW_VAULT_LOGIN_SUCCESS: "ADD_NEW_VAULT_LOGIN_SUCCESS",
    ADD_NEW_VAULT_LOGIN_FAILED: "ADD_NEW_VAULT_LOGIN_FAILED",
    ADD_VAULT_USER_REQUEST_REQUEST: "ADD_VAULT_USER_REQUEST_REQUEST",
    ADD_VAULT_USER_REQUEST_SUCCESS: "ADD_VAULT_USER_REQUEST_SUCCESS",
    ADD_VAULT_USER_REQUEST_FAILED: "ADD_VAULT_USER_REQUEST_FAILED",
    GET_VAULT_INVITE_DATA_REQUEST: "GET_VAULT_INVITE_DATA_REQUEST",
    GET_VAULT_INVITE_DATA_SUCCESS: "GET_VAULT_INVITE_DATA_SUCCESS",
    GET_VAULT_INVITE_DATA_FAILED: "GET_VAULT_INVITE_DATA_FAILED",
    VAULT_INVITE_ACCEPT_REQUEST: "VAULT_INVITE_ACCEPT_REQUEST",
    VAULT_INVITE_ACCEPT_SUCCESS: "VAULT_INVITE_ACCEPT_SUCCESS",
    VAULT_INVITE_ACCEPT_FAILED: "VAULT_INVITE_ACCEPT_FAILED",
}
